chore: always use userID for telemetry distinctID
akitasoftware/akita-cli pull request #261
Opened 2024-04-08 05:33 UTC by mudit-postman

Remove the check for emailID in the `getDistinctID()` function in `telemetry.go`. We will now always user userID, i.e. user's Postman UserID

2024-04-12 15:14 UTC, mgritter requested changes

2024-04-12 15:14 UTC, mgritter commented on telemetry/telemetry.go
> +			// User postman user's userID as distinctID for telemetry
Please fix the commenst above (line 116, 129) with what the current strategy is.

2024-04-12 15:16 UTC, mgritter commented on telemetry/telemetry.go
> +			// User postman user's userID as distinctID for telemetry
Looks like this is obsoleted by #262?

2024-04-15 08:35 UTC, mudit-postman commented
Closing, PR irrelevant now.

2024-04-15 08:35 UTC, closed without merging